development:
  oracle:
    host: localhost
    port: 1527
    database_name: DBNAME
    user: username
    password: password
  remote_request_api_key: 'changethis'

test:
  oracle:
    host: localhost
    port: 12345
    database_name: TEST
    user: test_user
    password: test_password
  remote_request_api_key: 'changethis'