name: CI

on:
  push:
    branches: [ '*' ]

jobs:
  ci-rails-app:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ruby-version: ['3.2.2']
    env:
      RAILS_ENV: test
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      NLS_LANG: AMERICAN_AMERICA.US7ASCII

    steps:
      - uses: actions/checkout@v3
      - name: Add --no-document option to .gemrc file to speed up bundle install
        run: "echo 'gem: --no-document' > ~/.gemrc"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run CI task
        run: bundle exec rake voyager_query:ci