name: CI

on:
  push:
    branches: [ '*' ]

jobs:
  ci-rails-app:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ruby-version: ['3.2.2']
    env:
      RAILS_ENV: test
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      NLS_LANG: AMERICAN_AMERICA.US7ASCII

    steps:
      - uses: actions/checkout@v3
      - name: Cache Oracle Downloads
        id: cache-oracle-downloads
        uses: actions/cache@v3
        with:
          path: /opt/oracle/downloads
          key: ${{ runner.os }}-oracle-download
      - name: Set up ruby-oci8 gem oracle dependencies
        run: |
          mkdir -p /opt/oracle/downloads
          cd /opt/oracle/downloads
          pwd
          if [ ! -f /opt/oracle/downloads/cache.present ]; then curl -O 'https://download.oracle.com/otn_software/linux/instantclient/211000/instantclient-basic-linux.x64-21.1.0.0.0.zip'; fi
          if [ ! -f /opt/oracle/downloads/cache.present ]; then curl -O 'https://download.oracle.com/otn_software/linux/instantclient/211000/instantclient-sdk-linux.x64-21.1.0.0.0.zip'; fi
          if [ ! -f /opt/oracle/downloads/cache.present ]; then curl -O 'https://download.oracle.com/otn_software/linux/instantclient/211000/instantclient-sqlplus-linux.x64-21.1.0.0.0.zip'; fi
          if [ ! -f /opt/oracle/downloads/cache.present ]; then touch cache.present; fi
          cd /opt/oracle
          find ./downloads -name '*.zip' -exec unzip {} \;
          echo $NLS_LANG
          ls -la /opt/oracle/instantclient_21_1
          echo "LD_LIBRARY_PATH=/opt/oracle/instantclient_21_1" >> $GITHUB_ENV
      - name: Add --no-document option to .gemrc file to speed up bundle install
        run: "echo 'gem: --no-document' > ~/.gemrc"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run CI task
        run: bundle exec rake voyager_query:ci